/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the repository of this plugin

THIS FILE IS PART OF THE LLM TEXT ASSISTANT OBSIDIAN PLUGIN
Copyright (C) s1t5
GPL-3.0-or-later (see LICENSE)
*/


"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  BUILTIN_ACTION_IDS: () => BUILTIN_ACTION_IDS,
  applyStreamToken: () => applyStreamToken,
  beginReplace: () => beginReplace,
  buildPromptParts: () => buildPromptParts,
  default: () => LlmTextAssistantPlugin2,
  getActionTitle: () => getActionTitle,
  getEditorSelection: () => getEditorSelection,
  showUndoToast: () => showUndoToast
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/i18n.ts
var messages = {
  de: {
    extensionName: "LLM Text Assistent",
    commandName: "LLM Text Assistent: Men\xFC \xF6ffnen",
    commandNameTranslate: "LLM Text Assistent: \xDCbersetzen",
    commandNameExpand: "LLM Text Assistent: Ausformulieren",
    commandNameSummarize: "LLM Text Assistent: Zusammenfassen",
    commandNameGrammar: "LLM Text Assistent: Rechtschreibung & Grammatik",
    actionTranslate: "\u{1F310} Ins $TARGET_LANGUAGE$ \xFCbersetzen",
    actionExpand: "\u270D\uFE0F Ausformulieren",
    actionSummarize: "\u{1F4CB} Zusammenfassen",
    actionGrammar: "\u2705 Rechtschreibung & Grammatik",
    menuFreePrompt: "\u{1F4AC} Freier Prompt",
    chatTitle: "\u{1F4AC} Freier Prompt",
    chatWelcomeWithContext: 'Text aus dem Editor wurde als Kontext geladen. Du kannst jetzt Anweisungen geben, z.B. "Verbessere den Text" oder "\xDCbersetze ins Englische".',
    chatWelcomeNoContext: "Beschreibe, was mit deinem Text passieren soll. Du kannst mehrere Anweisungen nacheinander senden. Klicke auf **\xDCbernehmen**, um das Ergebnis in den Editor einzuf\xFCgen.",
    chatInputPlaceholder: "Anweisung eingeben...",
    chatSend: "Senden",
    chatStop: "\u23F9 Stopp",
    chatApply: "\u2713 \xDCbernehmen",
    chatCopyLast: "\u29C9 Letzte Antwort kopieren",
    chatCopied: "\u2713 In die Zwischenablage kopiert",
    chatReset: "\u21BA Zur\xFCcksetzen",
    chatResetWithContext: "Chat zur\xFCckgesetzt. Text aus dem Editor wurde neu als Kontext geladen. Was m\xF6chtest du damit machen?",
    chatResetNoContext: "Chat zur\xFCckgesetzt. Was m\xF6chtest du mit deinem Text machen?",
    chatGenerating: "Generiere Antwort...",
    errorPrefix: "LLM Text Assistent: ",
    errorNoText: "Kein Text im Editor vorhanden",
    errorNoSelection: "Keine Auswahl im Editor",
    errorNoResult: "Kein generierter Text zum \xDCbernehmen vorhanden.",
    errorGeneric: "Unbekannter Fehler",
    requestCancelled: "Anfrage abgebrochen.",
    undoReplaced: "\u2713 Text ersetzt",
    undoButton: "R\xFCckg\xE4ngig",
    iconTooltipProcessing: "Verarbeite\u2026 Klicken zum Abbrechen",
    defaultTargetLanguage: "Englisch",
    defaultPromptTranslate: "Du bist ein \xDCbersetzungs-Werkzeug. \xDCbersetze den unterhalb markierten Text ins $TARGET_LANGUAGE$. Behalte die Formatierung, Abs\xE4tze und Zeilenumbr\xFCche genau bei. Gib NUR die \xDCbersetzung aus \u2013 keine Einleitung, keine Erkl\xE4rung, keine Meta-Kommentare.",
    defaultPromptExpand: "Du bist ein Text-Werkzeug. Formuliere die unterhalb markierten Stichpunkte oder Satzfragmente zu einem vollst\xE4ndigen, fl\xFCssigen Text aus. Behalte die Formatierung, Abs\xE4tze und Zeilenumbr\xFCche bei. Gib NUR den ausformulierten Text aus \u2013 keine Einleitung, keine Erkl\xE4rung, keine Meta-Kommentare.",
    defaultPromptSummarize: "Du bist ein Zusammenfassungs-Werkzeug. Fasse den unterhalb markierten Text kurz und pr\xE4gnant zusammen. Behalte die Formatierung, Abs\xE4tze und Zeilenumbr\xFCche bei. Gib NUR die Zusammenfassung aus \u2013 keine Einleitung, keine Erkl\xE4rung, keine Meta-Kommentare.",
    defaultPromptGrammar: "Du bist ein Korrektur-Werkzeug. Korrigiere Rechtschreibung, Grammatik und Zeichensetzung im unterhalb markierten Text. Behalte die Formatierung, Abs\xE4tze und Zeilenumbr\xFCche bei. Gib NUR den korrigierten Text aus \u2013 keine Einleitung, keine Erkl\xE4rung, keine Meta-Kommentare.",
    freePromptSystem: "Du bist ein hilfreicher Text-Assistent. Bearbeite und formuliere Text anhand der Anweisungen des Nutzers. Antworte nur mit dem verarbeiteten Text, ohne zus\xE4tzliche Erkl\xE4rungen, es sei denn, der Nutzer bittet darum.",
    freePromptContextIntro: "Der Nutzer hat folgenden Text aus dem Editor als Kontext geladen. Beziehe dich bei allen Anweisungen auf diesen Text:",
    settingsHeading: "LLM Text Assistent",
    settingsApiUrl: "API URL",
    settingsApiKey: "API Key",
    settingsModel: "Modell",
    settingsTemperature: "Temperature",
    settingsTimeout: "Timeout (Sekunden)",
    settingsTargetLanguage: "Zielsprache (\xDCbersetzen)",
    settingsPrompts: "\u{1F4DD} System-Prompts",
    settingsCustomActions: "\u26A1 Benutzerdefinierte Aktionen",
    settingsFreePrompt: "\u{1F4AC} Freier Prompt (Chat-Modus)",
    toastErrorPrefix: "Fehler: "
  },
  en: {
    extensionName: "LLM Text Assistant",
    commandName: "LLM Text Assistant: Open menu",
    commandNameTranslate: "LLM Text Assistant: Translate",
    commandNameExpand: "LLM Text Assistant: Expand",
    commandNameSummarize: "LLM Text Assistant: Summarize",
    commandNameGrammar: "LLM Text Assistant: Spelling & grammar",
    actionTranslate: "\u{1F310} Translate into $TARGET_LANGUAGE$",
    actionExpand: "\u270D\uFE0F Expand text",
    actionSummarize: "\u{1F4CB} Summarize",
    actionGrammar: "\u2705 Spelling & grammar",
    menuFreePrompt: "\u{1F4AC} Free prompt",
    chatTitle: "\u{1F4AC} Free Prompt",
    chatWelcomeWithContext: 'The text from the editor has been loaded as context. You can now give instructions, e.g. "Improve the text" or "Translate into German".',
    chatWelcomeNoContext: "Describe what should happen with your text. You can send multiple instructions in sequence. Click **Apply** to insert the result into the editor.",
    chatInputPlaceholder: "Type an instruction...",
    chatSend: "Send",
    chatStop: "\u23F9 Stop",
    chatApply: "\u2713 Apply",
    chatCopyLast: "\u29C9 Copy last response",
    chatCopied: "\u2713 Copied to clipboard",
    chatReset: "\u21BA Reset",
    chatResetWithContext: "Chat reset. The text from the editor has been reloaded as context. What would you like to do with it?",
    chatResetNoContext: "Chat reset. What would you like to do with your text?",
    chatGenerating: "Generating response...",
    errorPrefix: "LLM Text Assistant: ",
    errorNoText: "No text in the editor",
    errorNoSelection: "No selection in the editor",
    errorNoResult: "No generated text to apply.",
    errorGeneric: "Unknown error",
    requestCancelled: "Request cancelled.",
    undoReplaced: "\u2713 Text replaced",
    undoButton: "Undo",
    iconTooltipProcessing: "Processing\u2026 Click to cancel",
    defaultTargetLanguage: "English",
    defaultPromptTranslate: "You are a translation tool. Translate the text marked below into $TARGET_LANGUAGE$. Preserve formatting, paragraphs and line breaks exactly. Output ONLY the translation \u2013 no introduction, no explanation, no meta comments.",
    defaultPromptExpand: "You are a text tool. Turn the bullet points or sentence fragments marked below into a complete, fluent text. Preserve formatting, paragraphs and line breaks. Output ONLY the expanded text \u2013 no introduction, no explanation, no meta comments.",
    defaultPromptSummarize: "You are a summarization tool. Summarize the text marked below briefly and concisely. Preserve formatting, paragraphs and line breaks. Output ONLY the summary \u2013 no introduction, no explanation, no meta comments.",
    defaultPromptGrammar: "You are a proofreading tool. Correct spelling, grammar and punctuation in the text marked below. Preserve formatting, paragraphs and line breaks. Output ONLY the corrected text \u2013 no introduction, no explanation, no meta comments.",
    freePromptSystem: "You are a helpful text assistant. Edit and phrase text according to the user's instructions. Reply only with the processed text, without additional explanations, unless the user asks for them.",
    freePromptContextIntro: "The user has loaded the following text from the editor as context. Refer to this text for all instructions:",
    settingsHeading: "LLM Text Assistant",
    settingsApiUrl: "API URL",
    settingsApiKey: "API key",
    settingsModel: "Model",
    settingsTemperature: "Temperature",
    settingsTimeout: "Timeout (seconds)",
    settingsTargetLanguage: "Target language (translate)",
    settingsPrompts: "\u{1F4DD} System prompts",
    settingsCustomActions: "\u26A1 Custom actions",
    settingsFreePrompt: "\u{1F4AC} Free prompt (chat mode)",
    toastErrorPrefix: "Error: "
  }
};
var currentLang = "en";
function initI18n(obsidianLocale) {
  currentLang = obsidianLocale.toLowerCase().startsWith("de") ? "de" : "en";
}
function t(key, substitutions) {
  var _a, _b;
  let text = (_b = (_a = messages[currentLang][key]) != null ? _a : messages["en"][key]) != null ? _b : key;
  if (typeof substitutions === "string") {
    text = text.split("$TARGET_LANGUAGE$").join(substitutions);
  } else if (substitutions) {
    for (const [name, value] of Object.entries(substitutions)) {
      text = text.split(`$${name}$`).join(value);
    }
  }
  return text;
}
function isGerman() {
  return currentLang === "de";
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  apiUrl: "https://api.openai.com/v1/chat/completions",
  apiKey: "",
  model: "gpt-3.5-turbo",
  temperature: "0.3",
  timeoutSeconds: "60",
  targetLanguage: "",
  // resolved at runtime via i18n (locale-dependent default)
  promptTranslate: "",
  // locale-dependent defaults resolved at runtime
  promptExpand: "",
  promptSummarize: "",
  promptGrammar: "",
  customActions: [],
  freePromptEnabled: true
};

// src/llm.ts
var import_obsidian = require("obsidian");
var UserAbortError = class extends Error {
  constructor() {
    super("UserAbort");
    this.name = "UserAbortError";
  }
};
function sleep(ms) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}
function mapApiError(status, detail) {
  const german = isGerman();
  if (status === 401 || status === 403) {
    return german ? `API: Authentifizierung fehlgeschlagen (HTTP ${status}). Pr\xFCfe den API-Key.` : `API: authentication failed (HTTP ${status}). Check the API key.`;
  }
  if (status === 404) {
    return german ? `API: Endpunkt oder Modell nicht gefunden (HTTP 404). Pr\xFCfe URL und Modellname.` : `API: endpoint or model not found (HTTP 404). Check the URL and model name.`;
  }
  if (status === 429) {
    return german ? `API: Rate-Limit erreicht (HTTP 429). Bitte sp\xE4ter erneut versuchen.` : `API: rate limit reached (HTTP 429). Please try again later.`;
  }
  return german ? `API Fehler ${status}${detail ? ": " + detail : ""}` : `API error ${status}${detail ? ": " + detail : ""}`;
}
function extractApiDetail(errorText) {
  try {
    const parsed = JSON.parse(errorText);
    if (parsed && typeof parsed === "object" && "error" in parsed && parsed.error && typeof parsed.error === "object" && "message" in parsed.error && typeof parsed.error.message === "string") {
      return parsed.error.message;
    }
  } catch (e) {
  }
  return "";
}
function timeoutMessage(seconds) {
  return isGerman() ? `Zeit\xFCberschreitung nach ${seconds}s. L\xE4uft der Server bzw. ist der Endpunkt erreichbar?` : `Timeout after ${seconds}s. Is the server running / the endpoint reachable?`;
}
function networkErrorMessage() {
  return isGerman() ? "Netzwerkfehler: Der API-Endpunkt ist nicht erreichbar." : "Network error: the API endpoint is unreachable.";
}
async function fetchWithRetry(config, requestBody, signal) {
  const timeoutMs = Math.max(5, parseInt(config.timeoutSeconds || "60", 10) || 60) * 1e3;
  const maxAttempts = 3;
  let lastError = null;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    if (signal.aborted) {
      throw new UserAbortError();
    }
    const attemptController = new AbortController();
    const timeoutId = window.setTimeout(() => attemptController.abort(), timeoutMs);
    const onUserAbort = () => attemptController.abort();
    signal.addEventListener("abort", onUserAbort);
    try {
      const response = await performRequest(
        config,
        JSON.stringify(requestBody),
        attemptController.signal
      );
      window.clearTimeout(timeoutId);
      signal.removeEventListener("abort", onUserAbort);
      return response;
    } catch (err) {
      window.clearTimeout(timeoutId);
      signal.removeEventListener("abort", onUserAbort);
      if (signal.aborted) {
        throw new UserAbortError();
      }
      if (err instanceof UserAbortError) throw err;
      if (err instanceof Error && err.name === "AbortError") {
        lastError = new Error(timeoutMessage(timeoutMs / 1e3));
      } else {
        const failure = err;
        if (failure instanceof Error && typeof failure.status === "number") {
          const detail = extractApiDetail(failure.message || "");
          if ([400, 401, 403, 404].includes(failure.status) || failure.status >= 400 && failure.status < 500 && failure.status !== 408 && failure.status !== 429) {
            throw new Error(mapApiError(failure.status, detail));
          }
          lastError = new Error(mapApiError(failure.status, detail));
        } else {
          lastError = new Error(networkErrorMessage());
        }
      }
    }
    if (attempt < maxAttempts - 1) {
      await sleep(attempt === 0 ? 1e3 : 3e3);
    }
  }
  throw lastError || new Error(isGerman() ? "Unbekannter Fehler" : "Unknown error");
}
async function performRequest(config, body, signal) {
  if (signal.aborted) {
    throw new UserAbortError();
  }
  const headers = {
    "Content-Type": "application/json"
  };
  if (config.apiKey) {
    headers["Authorization"] = `Bearer ${config.apiKey}`;
  }
  const abortPromise = new Promise((_, reject) => {
    const onAbort = () => reject(new UserAbortError());
    if (signal.aborted) {
      onAbort();
      return;
    }
    signal.addEventListener("abort", onAbort, { once: true });
  });
  const doRequest = async () => {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: config.apiUrl,
        method: "POST",
        headers,
        body,
        throw: false
      });
      if (response.status >= 400) {
        const failure = new Error(response.text || "");
        failure.status = response.status;
        throw failure;
      }
      return {
        text: response.text,
        status: response.status,
        contentType: response.headers["content-type"] || response.headers["Content-Type"] || ""
      };
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") throw err;
      if (err instanceof Error && typeof err.status !== "number") {
        throw new Error(networkErrorMessage());
      }
      throw err;
    }
  };
  try {
    return await Promise.race([doRequest(), abortPromise]);
  } finally {
  }
}
async function streamResponse(completed, nextChunk, onToken, signal) {
  if (!completed.contentType.includes("text/event-stream")) {
    const content = extractMessageContent(completed.text);
    if (content === null) {
      throw new Error(isGerman() ? "Ung\xFCltige API-Antwort" : "Invalid API response");
    }
    if (content) onToken(content);
    return content;
  }
  let buffer = "";
  let fullText = "";
  const processLine = (line) => {
    if (!line.startsWith("data:")) return false;
    const payload = line.slice(5).trim();
    if (payload === "[DONE]") return true;
    const delta = extractDeltaContent(payload);
    if (typeof delta === "string" && delta.length > 0) {
      fullText += delta;
      onToken(delta);
    }
    return false;
  };
  if (nextChunk) {
    let done = false;
    while (!done) {
      if (signal.aborted) {
        throw new UserAbortError();
      }
      const chunk = await nextChunk();
      if (!chunk || chunk.done) break;
      buffer += chunk.text;
      let newlineIndex2;
      while ((newlineIndex2 = buffer.indexOf("\n")) >= 0) {
        let line = buffer.slice(0, newlineIndex2);
        buffer = buffer.slice(newlineIndex2 + 1);
        line = line.replace(/\r$/, "");
        if (processLine(line)) {
          return fullText;
        }
      }
    }
    return fullText;
  }
  buffer = completed.text;
  let newlineIndex;
  while ((newlineIndex = buffer.indexOf("\n")) >= 0) {
    let line = buffer.slice(0, newlineIndex);
    buffer = buffer.slice(newlineIndex + 1);
    line = line.replace(/\r$/, "");
    if (processLine(line)) {
      return fullText;
    }
  }
  return fullText;
}
function extractMessageContent(text) {
  var _a, _b, _c;
  try {
    const data = JSON.parse(text);
    const content = (_c = (_b = (_a = data == null ? void 0 : data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
    return typeof content === "string" ? content : null;
  } catch (e) {
    return null;
  }
}
function extractDeltaContent(payload) {
  var _a, _b, _c;
  try {
    const json = JSON.parse(payload);
    const delta = (_c = (_b = (_a = json == null ? void 0 : json.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.delta) == null ? void 0 : _c.content;
    return typeof delta === "string" ? delta : null;
  } catch (e) {
    return null;
  }
}
function isStreamUnsupported(err) {
  return err instanceof Error && /stream/i.test(err.message || "");
}
var LlmClient = class {
  constructor(config) {
    this.config = config;
  }
  createAbortController() {
    return new AbortController();
  }
  // Streaming chat completion with non-streaming fallback.
  // Mirrors processTextStreaming/processFreePromptStreaming from background.js.
  async streamChat(messages2, signal, callbacks) {
    const requestBody = {
      model: this.config.model,
      messages: messages2,
      temperature: parseFloat(this.config.temperature || "0.3"),
      stream: true
    };
    try {
      const response = await fetchWithRetry(this.config, requestBody, signal);
      const fullText = await streamResponse(
        response,
        null,
        callbacks.onToken,
        signal
      );
      callbacks.onDone(fullText);
    } catch (err) {
      if (isStreamUnsupported(err)) {
        try {
          const body = { ...requestBody };
          delete body.stream;
          const response = await fetchWithRetry(this.config, body, signal);
          const content = extractMessageContent(response.text);
          if (typeof content !== "string" || !content) {
            throw new Error(isGerman() ? "Ung\xFCltige API-Antwort" : "Invalid API response");
          }
          callbacks.onDone(content);
        } catch (fallbackErr) {
          this.dispatchError(fallbackErr, signal, callbacks);
        }
      } else {
        this.dispatchError(err, signal, callbacks);
      }
    }
  }
  dispatchError(err, signal, callbacks) {
    var _a;
    if (signal.aborted || err instanceof Error && err.name === "UserAbortError") {
      (_a = callbacks.onAborted) == null ? void 0 : _a.call(callbacks);
      return;
    }
    const message = err instanceof Error && err.message ? err.message : isGerman() ? "Unbekannter Fehler" : "Unknown error";
    callbacks.onError(message);
  }
};

// src/chat-modal.ts
var import_obsidian2 = require("obsidian");
function clipboardWrite(text) {
  void navigator.clipboard.writeText(text).catch(() => {
    new import_obsidian2.Notice(t("errorPrefix") + t("errorGeneric"));
  });
}
function wrapAssistantBubble(parent, bubble) {
  return parent.createDiv({ cls: "llmta-bubble-wrap" }, (wrapper) => {
    wrapper.appendChild(bubble);
  });
}
function addCopyButton(modal, wrapper, bubble) {
  wrapper.createEl("button", { cls: "llmta-copy-btn" }, (btn) => {
    btn.type = "button";
    btn.setText("\u29C9");
    btn.ariaLabel = "Copy";
    btn.addEventListener("click", (evt) => {
      evt.stopPropagation();
      const text = bubble.getText();
      if (!text.trim()) return;
      clipboardWrite(text);
      modal.generatedText = text;
      modal.markCopied(btn);
    });
  });
}
var FreePromptModal = class extends import_obsidian2.Modal {
  constructor(plugin, editor) {
    super(plugin.app);
    this.messages = [];
    this.abortController = null;
    // Latest assistant answer — public so the copy-button helper can set it
    // when an older bubble is copied.
    this.generatedText = "";
    this.isModalOpen = false;
    this.boundKeydown = null;
    this.plugin = plugin;
    this.editor = editor;
  }
  onOpen() {
    this.isModalOpen = true;
    this.contentEl.addClass("llmta-chat-modal");
    this.titleEl.setText(t("chatTitle"));
    const sel = getEditorSelection(this.editor);
    const contextText = sel.text.trim() ? sel.text : "";
    this.messages = this.buildInitialMessages(contextText);
    this.chatEl = this.contentEl.createDiv({ cls: "llmta-chat-log" });
    this.addBubble("system", contextText ? t("chatWelcomeWithContext") : t("chatWelcomeNoContext"));
    this.statusEl = this.contentEl.createDiv({ cls: "llmta-chat-status is-hidden" });
    const inputRow = this.contentEl.createDiv({ cls: "llmta-chat-input-row" });
    this.inputEl = inputRow.createEl("textarea", { cls: "llmta-chat-input" });
    this.inputEl.placeholder = t("chatInputPlaceholder");
    this.inputEl.rows = 2;
    const btnCol = inputRow.createDiv({ cls: "llmta-chat-buttons" });
    this.sendBtn = btnCol.createEl("button", {
      text: t("chatSend"),
      cls: "mod-cta llmta-chat-send"
    });
    this.stopBtn = btnCol.createEl("button", {
      text: t("chatStop"),
      cls: "llmta-chat-stop is-hidden"
    });
    this.sendBtn.addEventListener("click", () => this.handleSend());
    this.stopBtn.addEventListener("click", () => this.stopStreaming());
    this.inputEl.addEventListener("keydown", (evt) => {
      if (evt.key === "Enter" && !evt.shiftKey && !evt.ctrlKey && !evt.metaKey) {
        evt.preventDefault();
        this.handleSend();
      }
    });
    const footer = this.contentEl.createDiv({ cls: "llmta-chat-footer" });
    this.applyBtn = footer.createEl("button", {
      text: t("chatApply"),
      cls: "mod-cta"
    });
    this.applyBtn.addEventListener("click", () => this.handleApply());
    this.copyBtn = footer.createEl("button", { text: t("chatCopyLast") });
    this.copyBtn.addEventListener("click", () => this.copyLatest());
    this.resetBtn = footer.createEl("button", { text: t("chatReset") });
    this.resetBtn.addEventListener("click", () => this.handleReset());
    this.boundKeydown = (evt) => {
      if (!this.isModalOpen) return;
      if (evt.key !== "c" || !(evt.ctrlKey || evt.metaKey) || evt.shiftKey || evt.altKey) return;
      const active = document.activeElement;
      if (active && (active === this.inputEl || active.tagName === "TEXTAREA" || active.tagName === "INPUT")) return;
      if (this.chatEl && this.chatEl.contains(active)) return;
      const selection = window.getSelection();
      if (selection && selection.toString().trim()) return;
      if (!this.generatedText.trim()) return;
      evt.preventDefault();
      this.copyLatest();
    };
    document.addEventListener("keydown", this.boundKeydown, true);
  }
  onClose() {
    this.isModalOpen = false;
    if (this.boundKeydown) {
      document.removeEventListener("keydown", this.boundKeydown, true);
      this.boundKeydown = null;
    }
    this.stopStreaming();
  }
  // Mirrors buildInitialChatMessages from content.js
  buildInitialMessages(contextText) {
    let systemContent = t("freePromptSystem");
    if (contextText) {
      systemContent += "\n\n" + t("freePromptContextIntro") + "\n\n---\n" + contextText + "\n---";
    }
    return [{ role: "system", content: systemContent }];
  }
  addBubble(role, text) {
    const bubble = this.chatEl.createDiv({ cls: `llmta-bubble llmta-bubble-${role}` });
    bubble.setText(text);
    return bubble;
  }
  // Assistant bubbles get a floating copy button (wrapped for positioning).
  addAssistantBubble() {
    const holder = this.chatEl.createDiv({ cls: "llmta-bubble-holder" });
    const bubble = holder.createDiv({ cls: "llmta-bubble llmta-bubble-assistant" });
    const wrapper = wrapAssistantBubble(holder, bubble);
    addCopyButton(this, wrapper, bubble);
    return bubble;
  }
  copyLatest() {
    if (!this.generatedText.trim()) {
      new import_obsidian2.Notice(t("errorPrefix") + t("errorNoResult"));
      return;
    }
    clipboardWrite(this.generatedText);
    new import_obsidian2.Notice(t("chatCopied"));
  }
  markCopied(btn) {
    const prev = btn.getText();
    btn.setText("\u2713");
    window.setTimeout(() => btn.setText(prev), 1500);
  }
  setGenerating(generating) {
    this.sendBtn.toggleClass("is-hidden", generating);
    this.stopBtn.toggleClass("is-hidden", !generating);
    this.statusEl.toggleClass("is-hidden", !generating);
    if (generating) {
      this.statusEl.setText(t("chatGenerating"));
    }
  }
  handleSend() {
    const instruction = this.inputEl.value.trim();
    if (!instruction) return;
    if (this.abortController) return;
    this.addBubble("user", instruction);
    this.messages.push({ role: "user", content: instruction });
    this.inputEl.value = "";
    this.setGenerating(true);
    const bubble = this.addAssistantBubble();
    let first = true;
    this.abortController = new AbortController();
    const client = this.plugin.getClient();
    void client.streamChat(this.messages, this.abortController.signal, {
      onToken: (token) => {
        if (first) {
          bubble.setText(token);
          first = false;
        } else {
          bubble.setText(bubble.getText() + token);
        }
      },
      onDone: (fullText) => {
        this.generatedText = fullText;
        this.messages.push({ role: "assistant", content: fullText });
        this.abortController = null;
        this.setGenerating(false);
      },
      onError: (message) => {
        bubble.setText(t("errorPrefix") + message);
        this.abortController = null;
        this.setGenerating(false);
      },
      onAborted: () => {
        this.generatedText = bubble.getText();
        if (this.generatedText.trim()) {
          this.messages.push({ role: "assistant", content: this.generatedText });
        }
        this.abortController = null;
        this.setGenerating(false);
      }
    });
  }
  stopStreaming() {
    if (this.abortController) {
      this.abortController.abort();
    }
  }
  handleApply() {
    if (!this.generatedText.trim()) {
      new import_obsidian2.Notice(t("errorPrefix") + t("errorNoResult"));
      return;
    }
    const sel = getEditorSelection(this.editor);
    if (sel.isSelection) {
      this.editor.replaceRange(this.generatedText, sel.from, sel.to);
    } else {
      this.editor.replaceRange(this.generatedText, sel.from, sel.from);
    }
    this.close();
  }
  handleReset() {
    this.stopStreaming();
    this.messages = this.buildInitialMessages("");
    const sel = getEditorSelection(this.editor);
    if (sel.text.trim()) {
      this.messages = this.buildInitialMessages(sel.text);
      this.addBubble("system", t("chatResetWithContext"));
    } else {
      this.addBubble("system", t("chatResetNoContext"));
    }
    this.generatedText = "";
  }
};

// src/menu-modal.ts
var import_obsidian3 = require("obsidian");
var ActionMenuModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(plugin, editor) {
    super(plugin.app);
    this.plugin = plugin;
    this.editor = editor;
  }
  getItems() {
    const items = [...BUILTIN_ACTION_IDS];
    this.plugin.settings.customActions.forEach((action, idx) => {
      if (action.title && action.title.trim()) {
        items.push(`custom_${idx}`);
      }
    });
    if (this.plugin.settings.freePromptEnabled) {
      items.push("__free_prompt__");
    }
    return items;
  }
  getItemText(item) {
    if (item === "__free_prompt__") {
      return t("menuFreePrompt");
    }
    return getActionTitle(item, this.plugin.settings);
  }
  onChooseItem(item) {
    if (item === "__free_prompt__") {
      this.plugin.openFreePrompt(this.editor);
      return;
    }
    void this.plugin.runAction(this.editor, item);
  }
};

// src/main.ts
var BUILTIN_ACTION_IDS = ["translate", "expand", "summarize", "grammar"];
function getActionTitle(actionId, settings) {
  if (actionId.startsWith("custom_")) {
    const idx = parseInt(actionId.replace("custom_", ""), 10);
    const custom = settings.customActions[idx];
    if (!custom) return actionId;
    return `${custom.emoji || "\u26A1"} ${custom.title}`;
  }
  switch (actionId) {
    case "translate":
      return t("actionTranslate", { TARGET_LANGUAGE: settings.targetLanguage || t("defaultTargetLanguage") });
    case "expand":
      return t("actionExpand");
    case "summarize":
      return t("actionSummarize");
    case "grammar":
      return t("actionGrammar");
    default:
      return actionId;
  }
}
function resolveSystemPrompt(action, settings) {
  const targetLanguage = settings.targetLanguage || t("defaultTargetLanguage");
  if (action.startsWith("custom_")) {
    const idx = parseInt(action.replace("custom_", ""), 10);
    const custom = settings.customActions[idx];
    const prompt = (custom == null ? void 0 : custom.prompt) || "";
    if (!prompt.trim()) {
      throw new Error(
        isGerman() ? "Benutzerdefinierte Aktion hat keinen Prompt definiert." : "Custom action has no prompt defined."
      );
    }
    return prompt;
  }
  const builtinPrompts = {
    translate: settings.promptTranslate || t("defaultPromptTranslate", { TARGET_LANGUAGE: targetLanguage }),
    expand: settings.promptExpand || t("defaultPromptExpand"),
    summarize: settings.promptSummarize || t("defaultPromptSummarize"),
    grammar: settings.promptGrammar || t("defaultPromptGrammar")
  };
  let systemPrompt = builtinPrompts[action] || "";
  if (action === "translate") {
    systemPrompt = systemPrompt.split("{TARGET_LANGUAGE}").join(targetLanguage);
  }
  return systemPrompt;
}
function buildPromptParts(action, text, settings) {
  const systemPrompt = resolveSystemPrompt(action, settings);
  const german = isGerman();
  const fullSystemPrompt = german ? `${systemPrompt}

--- ZU VERARBEITENDER TEXT (keine Chat-Nachricht!) ---
${text}
--- ENDE TEXT ---

Verarbeite den obigen Text strikt gem\xE4\xDF der obigen Anweisung. Gib NUR das Ergebnis aus, ohne Einleitung, Erkl\xE4rung oder sonstige Zus\xE4tze.` : `${systemPrompt}

--- TEXT TO PROCESS (not a chat message!) ---
${text}
--- END TEXT ---

Process the text above strictly according to the instruction above. Output ONLY the result, without introduction, explanation or other additions.`;
  const userMessage = german ? "Verarbeite den Text." : "Process the text.";
  return [
    { role: "system", content: fullSystemPrompt },
    { role: "user", content: userMessage }
  ];
}
function getEditorSelection(editor) {
  const from = editor.getCursor("from");
  const to = editor.getCursor("to");
  const isSelection = from.line !== to.line || from.ch !== to.ch;
  if (isSelection) {
    return { from, to, text: editor.getRange(from, to), isSelection };
  }
  return { from, to, text: editor.getValue(), isSelection: false };
}
function editorEnd(editor) {
  const lastLine = editor.lastLine();
  return { line: lastLine, ch: editor.getLine(lastLine).length };
}
function beginReplace(editor, sel) {
  let from = { line: sel.from.line, ch: sel.from.ch };
  let to = { line: sel.to.line, ch: sel.to.ch };
  let originalText = sel.text;
  if (!sel.isSelection) {
    from = { line: 0, ch: 0 };
    to = editorEnd(editor);
    originalText = editor.getValue();
  }
  return {
    editor,
    from,
    to,
    originalText,
    insertOffset: editor.posToOffset(from),
    firstToken: true
  };
}
function applyStreamToken(handle, token) {
  const { editor } = handle;
  const pos = editor.offsetToPos(handle.insertOffset);
  if (handle.firstToken) {
    editor.replaceRange(token, handle.from, handle.to);
    handle.firstToken = false;
  } else {
    editor.replaceRange(token, pos, pos);
  }
  handle.insertOffset += token.length;
}
function showUndoToast(handle) {
  const { editor, from, originalText, insertOffset } = handle;
  const finalTo = editor.offsetToPos(insertOffset);
  const originalFrom = from;
  const notice = new import_obsidian4.Notice("", 8e3);
  const el = notice.messageEl;
  el.empty();
  el.addClass("llmta-undo-toast");
  el.createSpan({ text: t("undoReplaced") });
  const btn = el.createEl("button", { text: t("undoButton") });
  btn.addEventListener("click", () => {
    try {
      editor.replaceRange(originalText, originalFrom, finalTo);
    } catch (e) {
      editor.undo();
    }
    notice.hide();
  });
}
var LlmTextAssistantPlugin2 = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.runningNotice = null;
  }
  async onload() {
    initI18n(import_obsidian4.moment.locale());
    await this.loadSettings();
    this.addSettingTab(new LlmTextAssistantSettingTab(this.app, this));
    this.addRibbonIcon("sparkles", t("extensionName"), () => {
      this.openActionMenu();
    });
    this.addCommand({
      id: "open-menu",
      name: t("commandName"),
      editorCallback: () => this.openActionMenu()
    });
    const builtinCommands = {
      translate: t("commandNameTranslate"),
      expand: t("commandNameExpand"),
      summarize: t("commandNameSummarize"),
      grammar: t("commandNameGrammar")
    };
    for (const [actionId, name] of Object.entries(builtinCommands)) {
      this.addCommand({
        id: actionId,
        name,
        editorCallback: (editor) => this.runAction(editor, actionId)
      });
    }
    if (this.settings.freePromptEnabled) {
      this.addCommand({
        id: "free-prompt",
        name: `${t("menuFreePrompt")} (${t("commandName")})`,
        editorCallback: (editor) => this.openFreePrompt(editor)
      });
    }
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        this.addActionsToMenu(menu, editor);
      })
    );
  }
  async loadSettings() {
    const stored = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...stored != null ? stored : {} };
    if (!Array.isArray(this.settings.customActions)) {
      this.settings.customActions = [];
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getClient() {
    return new LlmClient({
      apiUrl: this.settings.apiUrl,
      apiKey: this.settings.apiKey,
      model: this.settings.model,
      temperature: this.settings.temperature,
      timeoutSeconds: this.settings.timeoutSeconds
    });
  }
  getActiveEditor() {
    var _a;
    const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
    if (editor) return editor;
    const leaf = this.app.workspace.getMostRecentLeaf();
    if (leaf && leaf.view.getViewType() === "markdown") {
      const mdView = leaf.view;
      if (mdView.editor) return mdView.editor;
    }
    return null;
  }
  addActionsToMenu(menu, editor) {
    menu.addSeparator();
    for (const actionId of BUILTIN_ACTION_IDS) {
      menu.addItem(
        (item) => item.setTitle(getActionTitle(actionId, this.settings)).setIcon("sparkles").onClick(() => {
          void this.runAction(editor, actionId);
        })
      );
    }
    this.settings.customActions.forEach((action, idx) => {
      if (action.title && action.title.trim()) {
        menu.addItem(
          (item) => item.setTitle(getActionTitle(`custom_${idx}`, this.settings)).onClick(() => {
            void this.runAction(editor, `custom_${idx}`);
          })
        );
      }
    });
    if (this.settings.freePromptEnabled) {
      menu.addItem(
        (item) => item.setTitle(t("menuFreePrompt")).onClick(() => {
          this.openFreePrompt(editor);
        })
      );
    }
  }
  openActionMenu() {
    const editor = this.getActiveEditor();
    if (!editor) {
      new import_obsidian4.Notice(t("errorPrefix") + t("errorNoText"));
      return;
    }
    new ActionMenuModal(this, editor).open();
  }
  openFreePrompt(editor) {
    new FreePromptModal(this, editor).open();
  }
  // Run a built-in or custom action on the current selection (or the whole
  // note when nothing is selected) with live streaming replacement.
  async runAction(editor, actionId) {
    const sel = getEditorSelection(editor);
    if (!sel.text.trim()) {
      new import_obsidian4.Notice(t("errorPrefix") + t("errorNoText"));
      return;
    }
    let messages2;
    try {
      messages2 = buildPromptParts(actionId, sel.text, this.settings);
    } catch (err) {
      new import_obsidian4.Notice(t("errorPrefix") + (err.message || t("errorGeneric")));
      return;
    }
    const controller = new AbortController();
    this.showProcessingNotice(controller);
    const handle = beginReplace(editor, sel);
    const client = this.getClient();
    await client.streamChat(messages2, controller.signal, {
      onToken: (token) => applyStreamToken(handle, token),
      onDone: () => {
        this.hideProcessingNotice();
        showUndoToast(handle);
      },
      onError: (message) => {
        this.hideProcessingNotice();
        new import_obsidian4.Notice(t("errorPrefix") + message, 8e3);
      },
      onAborted: () => {
        this.hideProcessingNotice();
        new import_obsidian4.Notice(t("requestCancelled"));
      }
    });
  }
  // "Processing… Click to cancel" toast, ported from the extension's
  // floating loading icon.
  showProcessingNotice(controller) {
    const notice = new import_obsidian4.Notice(t("iconTooltipProcessing"), 0);
    notice.messageEl.addEventListener("click", () => {
      controller.abort();
      this.hideProcessingNotice();
    });
    this.runningNotice = notice;
  }
  hideProcessingNotice() {
    if (this.runningNotice) {
      this.runningNotice.hide();
      this.runningNotice = null;
    }
  }
};
var LlmTextAssistantSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  // Declarative settings for Obsidian's settings search (1.13.0+).
  // Mirrors the imperative display() tab; the fallback rendering below stays
  // authoritative for users on older app versions.
  getSettingDefinitions() {
    const german = isGerman();
    const s = this.plugin.settings;
    const text = (key, name, desc, placeholder) => {
      var _a;
      return {
        name,
        desc,
        control: { type: "text", key, defaultValue: String((_a = s[key]) != null ? _a : ""), placeholder }
      };
    };
    const textArea = (key, name, desc) => {
      var _a;
      return {
        name,
        desc,
        control: { type: "textarea", key, defaultValue: String((_a = s[key]) != null ? _a : "") }
      };
    };
    return [
      {
        type: "group",
        heading: t("settingsHeading"),
        items: [
          text(
            "apiUrl",
            t("settingsApiUrl"),
            german ? "z. B. OpenAI, Ollama (http://localhost:11434/v1/chat/completions) oder LM Studio" : "e.g. OpenAI, Ollama (http://localhost:11434/v1/chat/completions) or LM Studio",
            "https://api.openai.com/v1/chat/completions"
          ),
          text(
            "apiKey",
            t("settingsApiKey"),
            german ? "Bei lokalen Endpunkten leer lassen" : "Leave empty for local endpoints",
            "sk-..."
          ),
          text(
            "model",
            t("settingsModel"),
            german ? "z. B. gpt-4, llama3.1, mistral" : "e.g. gpt-4, llama3.1, mistral",
            "gpt-3.5-turbo"
          ),
          text(
            "temperature",
            t("settingsTemperature"),
            german ? "0 = deterministisch, 2 = sehr kreativ (Standard: 0.3)" : "0 = deterministic, 2 = very creative (default: 0.3)",
            "0.3"
          ),
          text(
            "timeoutSeconds",
            t("settingsTimeout"),
            german ? "Maximale Wartezeit pro Anfrage (Standard: 60)" : "Maximum wait time per request (default: 60)",
            "60"
          ),
          text(
            "targetLanguage",
            t("settingsTargetLanguage"),
            german ? "Sprache, in die \xFCbersetzt wird, z. B. Englisch, Deutsch, Franz\xF6sisch" : "Language to translate into, e.g. English, German, French",
            t("defaultTargetLanguage")
          )
        ]
      },
      {
        type: "group",
        heading: t("settingsPrompts"),
        items: [
          textArea(
            "promptTranslate",
            t("actionTranslate", { TARGET_LANGUAGE: s.targetLanguage || t("defaultTargetLanguage") }),
            german ? "Platzhalter {TARGET_LANGUAGE} wird zur Laufzeit durch die Zielsprache ersetzt. Feld leeren = Standard-Prompt." : "The {TARGET_LANGUAGE} placeholder is replaced with the target language at runtime. Empty field = default prompt."
          ),
          textArea(
            "promptExpand",
            t("actionExpand"),
            german ? "Feld leeren = Standard-Prompt." : "Empty field = default prompt."
          ),
          textArea(
            "promptSummarize",
            t("actionSummarize"),
            german ? "Feld leeren = Standard-Prompt." : "Empty field = default prompt."
          ),
          textArea(
            "promptGrammar",
            t("actionGrammar"),
            german ? "Feld leeren = Standard-Prompt." : "Empty field = default prompt."
          )
        ]
      },
      {
        type: "group",
        heading: t("settingsCustomActions"),
        items: [
          {
            name: t("settingsCustomActions"),
            desc: german ? "Definiere eigene Aktionen mit Emoji, Titel und Prompt. Diese erscheinen im Men\xFC und im Kontextmen\xFC des Editors." : "Define your own actions with emoji, title and prompt. They appear in the menu and the editor context menu.",
            render: (setting) => {
              setting.setDesc(
                german ? "Verwalte die eigenen Aktionen auf der Plugin-Einstellungsseite." : "Manage custom actions on the plugin settings page."
              );
            }
          }
        ]
      },
      {
        type: "group",
        heading: t("settingsFreePrompt"),
        items: [
          {
            name: german ? "Freien Prompt im Men\xFC anzeigen" : "Show free prompt in the menu",
            desc: t("settingsFreePrompt"),
            control: { type: "toggle", key: "freePromptEnabled", defaultValue: true }
          }
        ]
      }
    ];
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName(t("settingsHeading")).setHeading();
    new import_obsidian4.Setting(containerEl).setName(t("settingsApiUrl")).setDesc(
      isGerman() ? "z. B. OpenAI (https://api.openai.com/v1/chat/completions), Ollama (http://localhost:11434/v1/chat/completions) oder LM Studio" : "e.g. OpenAI (https://api.openai.com/v1/chat/completions), Ollama (http://localhost:11434/v1/chat/completions) or LM Studio"
    ).addText((text) => {
      text.setValue(this.plugin.settings.apiUrl).onChange(async (value) => {
        this.plugin.settings.apiUrl = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("settingsApiKey")).setDesc(
      isGerman() ? "Bei lokalen Endpunkten leer lassen" : "Leave empty for local endpoints"
    ).addText((text) => {
      text.setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("settingsModel")).setDesc(
      isGerman() ? "z. B. gpt-4, llama3.1, mistral" : "e.g. gpt-4, llama3.1, mistral"
    ).addText((text) => {
      text.setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("settingsTemperature")).setDesc(
      isGerman() ? "0 = deterministisch, 2 = sehr kreativ (Standard: 0.3)" : "0 = deterministic, 2 = very creative (default: 0.3)"
    ).addText((text) => {
      text.setValue(this.plugin.settings.temperature).onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("settingsTimeout")).setDesc(
      isGerman() ? "Maximale Wartezeit pro Anfrage (Standard: 60)" : "Maximum wait time per request (default: 60)"
    ).addText((text) => {
      text.setValue(this.plugin.settings.timeoutSeconds).onChange(async (value) => {
        this.plugin.settings.timeoutSeconds = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("settingsTargetLanguage")).setDesc(
      isGerman() ? "Sprache, in die \xFCbersetzt wird, z. B. Englisch, Deutsch, Franz\xF6sisch" : "Language to translate into, e.g. English, German, French"
    ).addText((text) => {
      text.setValue(this.plugin.settings.targetLanguage || t("defaultTargetLanguage")).onChange(async (value) => {
        this.plugin.settings.targetLanguage = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("settingsPrompts")).setHeading();
    const promptFields = [
      {
        key: "promptTranslate",
        name: t("actionTranslate", { TARGET_LANGUAGE: this.plugin.settings.targetLanguage || t("defaultTargetLanguage") }),
        fallback: t("defaultPromptTranslate", { TARGET_LANGUAGE: "{TARGET_LANGUAGE}" })
      },
      { key: "promptExpand", name: t("actionExpand"), fallback: t("defaultPromptExpand") },
      { key: "promptSummarize", name: t("actionSummarize"), fallback: t("defaultPromptSummarize") },
      { key: "promptGrammar", name: t("actionGrammar"), fallback: t("defaultPromptGrammar") }
    ];
    for (const { key, name, fallback } of promptFields) {
      const setting = new import_obsidian4.Setting(containerEl).setName(name);
      if (key === "promptTranslate") {
        setting.setDesc(
          isGerman() ? "Platzhalter {TARGET_LANGUAGE} wird zur Laufzeit durch die Zielsprache ersetzt. Feld leeren = Standard-Prompt." : "The {TARGET_LANGUAGE} placeholder is replaced with the target language at runtime. Empty field = default prompt."
        );
      }
      setting.addTextArea((text) => {
        text.setValue(this.plugin.settings[key] || fallback).onChange(async (value) => {
          this.plugin.settings[key] = value;
          await this.plugin.saveSettings();
        });
        text.inputEl.rows = 4;
        text.inputEl.addClass("llmta-settings-textarea");
      });
    }
    new import_obsidian4.Setting(containerEl).setName(t("settingsCustomActions")).setHeading();
    new import_obsidian4.Setting(containerEl).setDesc(
      isGerman() ? "Definiere eigene Aktionen mit Emoji, Titel und Prompt. Diese erscheinen im Men\xFC und im Kontextmen\xFC des Editors." : "Define your own actions with emoji, title and prompt. They appear in the menu and the editor context menu."
    );
    const renderCustomActions = () => {
      listEl.empty();
      this.plugin.settings.customActions.forEach((action, idx) => {
        const wrapper = listEl.createDiv({ cls: "llmta-custom-action" });
        const row = wrapper.createDiv({ cls: "llmta-custom-action-row" });
        const emojiInput = row.createEl("input", { type: "text", cls: "llmta-emoji-input" });
        emojiInput.value = action.emoji || "\u26A1";
        const titleInput = row.createEl("input", {
          type: "text",
          placeholder: isGerman() ? "Aktionstitel" : "Action title"
        });
        titleInput.value = action.title || "";
        const promptArea = wrapper.createEl("textarea", {
          cls: "llmta-prompt-textarea"
        });
        promptArea.placeholder = isGerman() ? "System-Prompt f\xFCr diese Aktion..." : "System prompt for this action...";
        promptArea.rows = 2;
        promptArea.value = action.prompt || "";
        const removeBtn = row.createEl("button", {
          text: isGerman() ? "\u{1F5D1} Entfernen" : "\u{1F5D1} Remove",
          cls: "llmta-remove-btn"
        });
        const update = () => {
          this.plugin.settings.customActions[idx] = {
            emoji: emojiInput.value,
            title: titleInput.value,
            prompt: promptArea.value
          };
          void this.plugin.saveSettings();
        };
        emojiInput.addEventListener("change", update);
        titleInput.addEventListener("change", update);
        promptArea.addEventListener("change", update);
        removeBtn.addEventListener("click", () => {
          this.plugin.settings.customActions.splice(idx, 1);
          void this.plugin.saveSettings();
          renderCustomActions();
        });
      });
    };
    const listEl = containerEl.createDiv();
    renderCustomActions();
    new import_obsidian4.Setting(containerEl).addButton((btn) => {
      btn.setButtonText(isGerman() ? "\uFF0B Neue Aktion hinzuf\xFCgen" : "\uFF0B Add new action").onClick(() => {
        this.plugin.settings.customActions.push({ emoji: "\u26A1", title: "", prompt: "" });
        void this.plugin.saveSettings();
        renderCustomActions();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("settingsFreePrompt")).setHeading();
    new import_obsidian4.Setting(containerEl).setName(
      isGerman() ? "Freien Prompt im Men\xFC anzeigen" : "Show free prompt in the menu"
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.freePromptEnabled).onChange(async (value) => {
        this.plugin.settings.freePromptEnabled = value;
        await this.plugin.saveSettings();
      });
    });
  }
};
